try {
  hello()
} catch (error) {
  console.log('Aqui hay un error', error)
}
